# Generated by Django 4.0.5 on 2022-06-05 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rub_usd_uni', models.FloatField(default=None)),
                ('rub_eur_uni', models.FloatField(default=None)),
                ('rub_amd_uni', models.FloatField(default=None)),
                ('usd_amd_sas', models.FloatField(default=None)),
                ('eur_amd_sas', models.FloatField(default=None)),
                ('last_update', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
