# Generated by Django 4.0.5 on 2022-06-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='last_update',
            field=models.TimeField(default='20:07:48'),
        ),
    ]
